# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FFAudX.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 283)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/d/ffmpeg-logo_400x400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_convert = QtWidgets.QPushButton(self.frame)
        self.btn_convert.setGeometry(QtCore.QRect(270, 20, 91, 31))
        self.btn_convert.setObjectName("btn_convert")
        self.queue_list = MyListWidget(self.frame)
        self.queue_list.setGeometry(QtCore.QRect(10, 10, 211, 221))
        self.queue_list.setObjectName("queue_list")
        self.chk_video = QtWidgets.QCheckBox(self.frame)
        self.chk_video.setGeometry(QtCore.QRect(232, 72, 71, 22))
        self.chk_video.setObjectName("chk_video")
        self.combo_video = QtWidgets.QComboBox(self.frame)
        self.combo_video.setGeometry(QtCore.QRect(310, 70, 81, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_video.sizePolicy().hasHeightForWidth())
        self.combo_video.setSizePolicy(sizePolicy)
        self.combo_video.setObjectName("combo_video")
        self.combo_video.addItem("")
        self.combo_video.setItemText(0, "")
        self.combo_video.addItem("")
        self.combo_video.addItem("")
        self.combo_video.addItem("")
        self.combo_video.addItem("")
        self.combo_video.addItem("")
        self.combo_audio = QtWidgets.QComboBox(self.frame)
        self.combo_audio.setGeometry(QtCore.QRect(310, 110, 81, 27))
        self.combo_audio.setObjectName("combo_audio")
        self.combo_audio.addItem("")
        self.combo_audio.setItemText(0, "")
        self.combo_audio.addItem("")
        self.combo_audio.addItem("")
        self.combo_audio.addItem("")
        self.chk_audio = QtWidgets.QCheckBox(self.frame)
        self.chk_audio.setGeometry(QtCore.QRect(232, 112, 71, 22))
        self.chk_audio.setObjectName("chk_audio")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(230, 150, 171, 20))
        self.label.setObjectName("label")
        self.txt_save = QtWidgets.QLineEdit(self.frame)
        self.txt_save.setGeometry(QtCore.QRect(232, 176, 169, 27))
        self.txt_save.setObjectName("txt_save")
        self.progress_bar = QtWidgets.QProgressBar(self.frame)
        self.progress_bar.setGeometry(QtCore.QRect(232, 209, 169, 25))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FFAudX"))
        self.btn_convert.setText(_translate("MainWindow", "Convert"))
        self.chk_video.setText(_translate("MainWindow", "Video"))
        self.combo_video.setItemText(1, _translate("MainWindow", "mp4"))
        self.combo_video.setItemText(2, _translate("MainWindow", "avi"))
        self.combo_video.setItemText(3, _translate("MainWindow", "wma"))
        self.combo_video.setItemText(4, _translate("MainWindow", "mov"))
        self.combo_video.setItemText(5, _translate("MainWindow", "flv"))
        self.combo_audio.setItemText(1, _translate("MainWindow", "mp3"))
        self.combo_audio.setItemText(2, _translate("MainWindow", "wav"))
        self.combo_audio.setItemText(3, _translate("MainWindow", "FLAC"))
        self.chk_audio.setText(_translate("MainWindow", "Audio"))
        self.label.setText(_translate("MainWindow", "Save Destination"))
        self.txt_save.setText(_translate("MainWindow", "Save Destination..."))

from MyListWidget import MyListWidget
